<?php
/**
 * Language labels for plugin "tx_x4equalificationgeneral_pi1"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'listFieldHeader_organizer' => 'Organizer',
		'listFieldHeader_title' => 'Title',
		'listFieldHeader_type' => 'Type',
		'listFieldHeader_finished' => 'Finished',
		'listFieldHeader_abstract' => 'Abstract ',
		'listFieldHeader_pictures' => 'Pictures',
		'listFieldHeader_abortet' => 'Abortet',
		'listFieldHeader_student' => 'Student',
		'listFieldHeader_firstname' => 'Firstname',
		'listFieldHeader_lastname' => 'Lastname',
		'listFieldHeader_lUid' => 'Details',
		'listFieldHeader_address' => 'Address',
		'listFieldHeader_email' => 'E-mail',
		'listFieldHeader_phone' => 'Phone',
		'list_mode_1' => 'Mode 1',
		'list_mode_2' => 'Mode 2',
		'list_mode_3' => 'Mode 3',
		'back' => 'Back',
		'pi_list_back_to_list' => 'back',
		'pi_list_browseresults_prev' => '< Previous',
		'pi_list_browseresults_page' => 'Page',
		'pi_list_browseresults_next' => 'Next >',
		'pi_list_browseresults_displays' => 'Displaying results ###FROM### to ###TO### out of ###OUT_OF###',
		'pi_list_searchBox_search' => 'Search',
		'qualification_workings_of' => 'Graduation paper - ',

		'type_liz_sing' => 'Lizentiatsarbeit',
		'type_ma_sing' => 'MA-Arbeit',
		'type_diss_sing' => 'Dissertation',
		'type_liz_plur' => 'Lizentiatsarbeiten',
		'type_ma_plur' => 'MA-Arbeiten',
		'type_diss_plur' => 'Dissertationen',
		'more_link' => 'more..',
		'profListLink' => 'List by Professors',

		'optionCurrent' => 'current',
		'optionFinished' => 'finished',
		'optionAll' => 'all',

		'createQualification' => 'Create graduation paper',
		'editRecord' => '<img src="fileadmin/histsem/_templates/images/icon_edit.gif" height="9" width="9"> Edit',
		'removeRecord' => '<img src="fileadmin/histsem/_templates/images/icon_delete.gif" height="9" width="9"> Remove',
	),
	'de' => Array (
		'listFieldHeader_organizer' => 'Betreuer',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_type' => 'Typ',
		'listFieldHeader_finished' => 'Beendet',
		'listFieldHeader_abstract' => 'Abstract',
		'listFieldHeader_pictures' => 'Bilder',
		'listFieldHeader_abortet' => 'Abgebrochen',
		'listFieldHeader_student' => 'Student',
		'listFieldHeader_firstname' => 'Vorname',
		'listFieldHeader_lastname' => 'Autor',
		'listFieldHeader_lUid' => 'Details',
		'listFieldHeader_address' => 'Adresse',
		'listFieldHeader_email' => 'E-Mail',
		'listFieldHeader_phone' => 'Telefon',
		'list_mode_1' => 'Mode 1',
		'list_mode_2' => 'Mode 2',
		'list_mode_3' => 'Mode 3',
		'back' => 'Back',
		'pi_list_back_to_list' => '< zurück',
		'pi_list_browseresults_first' => '<< Anfang',
		'pi_list_browseresults_prev' => '< Zurück',
		'pi_list_browseresults_page' => '',
		'pi_list_browseresults_next' => 'Weiter >',
		'pi_list_browseresults_last' => 'Ende >>',
		'pi_list_browseresults_displays' => 'Zeige Resultate ###FROM###-###TO### von ###OUT_OF### Abschlussarbeiten<br/>Die Liste lässt sich durch einen Klick auf den Spaltennamen sortieren.',
		'pi_list_searchBox_search' => 'Suchen',
		'qualification_workings_of' => 'Betreute Abschlussarbeiten - ',
		'profListLink' => 'Liste nach Betreuern',

		'type_liz_sing' => 'Lizentiatsarbeit',
		'type_ma_sing' => 'MA-Arbeit',
		'type_diss_sing' => 'Dissertation',
		'type_running' => 'Laufende ',
		'type_terminated' => 'Abgeschlossene ',
		'type_liz_plur' => 'Lizentiatsarbeiten',
		'type_ma_plur' => 'MA-Arbeiten',
		'type_diss_plur' => 'Dissertationen',
		'more_link' => 'mehr..',
		'optionCurrent' => 'laufend',
		'optionFinished' => 'abgeschlossen',
		'optionAll' => 'alle',
		'createQualification' => 'Abschlussarbeit erfassen',
		'editRecord' => '<img src="typo3conf/ext/x4equalificationgeneral/images/icon_edit.gif" height="9" width="9" alt="Diese Abschlussarbeit bearbeiten" title="Diese Abschlussarbeit bearbeiten" /> Bearbeiten',
		'removeRecord' => '<img src="typo3conf/ext/x4equalificationgeneral/images/icon_delete.gif" height="9" width="9" alt="Diese Abschlussarbeit löschen" title="Diese Abschlussarbeit löschen" /> Löschen',
		'pdfLinkText' => 'Liste als Pdf herunterladen',
	),

);
?>