<?php
/**
 * Language labels for plugin "tx_publics_pi2"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'subCatSelection.heading' => 'Publication type',
		'subCatSelection.firstSelection' => 'Select...',
		'subCatSelection.submit' => 'Next',
		'newForm.submit' => 'Create',
		'searchAuthor.searchLabel' => 'Search',
		'searchAuthor.submit' => 'Search',
		'searchAuthor.addLabel' => 'Add',
		'searchAuthor.close' => 'Close',
		'searchAuthor.noResultFound' => 'No results found',
		'searchStudent.searchLabel' => 'Search',
		'searchStudent.submit' => 'Search',
		'searchStudent.addLabel' => 'Add',
		'searchStudent.editLabel' => 'Edit',
		'searchStudent.close' => 'Close',
		'addPublisher' => 'Add publisher',
		'remPublisher' => 'Remove',
		'extPublisher' => 'External publisher',
		'extPublisher.name' => 'Name/Institute',
		'extPublisher.firstname' => 'Firstname',
		'addAuthor' => 'Add author',
		'remAuthor' => 'Remove',
		'extAuthor' => 'External authors',
		'extAuthor.name' => 'Name/Institute',
		'extAuthor.firstname' => 'Firstname',
		
		
		'category_sub' => 'Category',	
		'authors' => 'Authors',	
		'authors_ext' => 'External Authors (Name, Firstname (LineBreak) Name, Firstname...)',	
		'publishers' => 'Publishers',	
		'publishers_ext' => 'External Publishers  (Name, Firstname (LineBreak) Name, Firstname...)',	
		'title' => 'Title',
		'titleExample' => '(incl. subtitle)',
		'location' => 'Location',
		'locationExample' => '(Zürich; Basel / Bern)',
		'run' => 'Run',	
		'year' => 'Year of publication',	
		'volume' => 'Title and band',	
		'magazine_title' => 'Magazin title',	
		'magazine_year' => 'Magazine year',	
		'magazine_issue' => 'Magazine issue',	
		'anthology_title' => 'Anthology title',	
		'anthology_publisher' => 'Anthology publisher',	
		'pages' => 'Pages',	
		'event_date' => 'Event/Date',	
		'other_redaction' => 'Other Redaction',
		'editForm.submit' => 'Save changes',
		'editForm.back' => 'Back',
		
		'headingEdit' => 'Edit publication',
		'headingNew' => 'New publication',
	),
	'de' => Array (
		'subCatSelection.heading' => 'Publikationstyp',
		'subCatSelection.firstSelection' => 'Auswahl...',
		'subCatSelection.submit' => 'Weiter',
		'newForm.submit' => 'Erstellen',
		'searchAuthor.searchLabel' => 'Suche interne AutorIn',
		'searchAuthor.submit' => 'Suchen',
		'searchAuthor.addLabel' => 'Hinzufügen',
		'searchAuthor.close' => 'Schliessen',
		'searchAuthor.noResultFound' => 'Keine Ergebnisse gefunden.',
		'addAuthor' => 'Autor hinzufügen',
		'remAuthor' => 'Entfernen',
		'extAuthor' => 'Externe Personen',
		'publisherChBoxLabel' => 'Hrsg.',
		'searchStudent.searchLabel' => 'Suche erfassten Studenten/-in',
		'searchStudent.searchLabel' => 'Suche',
		'searchStudent.submit' => 'Suche',
		'searchStudent.addLabel' => 'Hinzufügen',
		'searchStudent.editLabel' => 'Bearbeiten',
		'searchStudent.close' => 'Schliessen',
		'addPublisher' => 'Herausgeber hinzufügen',
		'remPublisher' => 'Entfernen',
		'extPublisher' => 'Externe Herausgeber',
		'extPublisher.name' => 'Name/Institut',
		'extPublisher.firstname' => 'Vorname',
		'extAuthor.name' => 'Name/Institut',
		'extAuthor.firstname' => 'Vorname',
		
		'category_sub' => 'Publikationstyp',	
		'auth_publ' => 'Beiteiligte Personen sind',
		'authors' => 'Interne Personen',	
		'authors_ext' => 'Externe Autoren (Name, Vorname (Zeilenumbruch) Name, Vorname...)',	
		'publishers' => 'Herausgeber',	
		'publishers_ext' => 'Externe Autoren (Name, Vorname (Zeilenumbruch) Name, Vorname...)',	
		'title' => 'Titel',
		'titleExample' => '(mit Untertitel)',	
		'location' => 'Ort',	
		'locationExample' => '(Zürich; Basel / Bern)',	
		'run' => 'Auflage',
		'runExample' => 'leer bei 1. Aufl., 2. Aufl. 3., erw. Aufl.',
		'year' => 'Erscheinungsjahr',
		'yearExample' => '2000; 2000-2005; 2000-',
		'volume' => 'Reihentitel und Band',
		'volumeExample' => 'Basler Beiträge zur Geschichtswissenschaft 173',
	
		'magazine_title' => 'Zeitschriftentitel',
		'magazine_titleExample' => 'Traverse',
		'magazine_year' => 'Zeitschriftenjahrgang',	
		'magazine_yearExample' => '78',	
		'magazine_issue' => 'Zeitschriftenheft',	
		'magazine_issueExample' => '3, IV',	
		'anthology_title' => 'Sammelbandtitel (auch Lexikontitel)',	
		'anthology_publisher' => 'Herausgeber des Sammelbands',	
		'pages' => 'Seiten',
		'pagesExample' => '55-78, 678ff',
		'event_date' => 'Anlass/Datum',	
		'other_redaction' => 'Andere Ausgabe',	
		'tt_content.list_type_pi1' => 'Ansicht der Publikationen',	
		'tt_content.list_type_pi2' => 'Eingabe der Publikationen',
		'editForm.submit' => 'Änderungen speichern',
		'editForm.back' => 'Abbrechen',
		
		'headingEdit' => 'Publikation bearbeiten',
		'headingNew' => 'Publikation erfassen',
	),
);
?>